# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kv_store.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ekv_store.proto\"\x19\n\nGetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"-\n\x0bGetResponse\x12\r\n\x05value\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\"(\n\nPutRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x1e\n\x0bPutResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x1c\n\rDeleteRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"!\n\x0e\x44\x65leteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32~\n\rKeyValueStore\x12 \n\x03Get\x12\x0b.GetRequest\x1a\x0c.GetResponse\x12 \n\x03Put\x12\x0b.PutRequest\x1a\x0c.PutResponse\x12)\n\x06\x44\x65lete\x12\x0e.DeleteRequest\x1a\x0f.DeleteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kv_store_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETREQUEST']._serialized_start=18
  _globals['_GETREQUEST']._serialized_end=43
  _globals['_GETRESPONSE']._serialized_start=45
  _globals['_GETRESPONSE']._serialized_end=90
  _globals['_PUTREQUEST']._serialized_start=92
  _globals['_PUTREQUEST']._serialized_end=132
  _globals['_PUTRESPONSE']._serialized_start=134
  _globals['_PUTRESPONSE']._serialized_end=164
  _globals['_DELETEREQUEST']._serialized_start=166
  _globals['_DELETEREQUEST']._serialized_end=194
  _globals['_DELETERESPONSE']._serialized_start=196
  _globals['_DELETERESPONSE']._serialized_end=229
  _globals['_KEYVALUESTORE']._serialized_start=231
  _globals['_KEYVALUESTORE']._serialized_end=357
# @@protoc_insertion_point(module_scope)
